// Generated by Haxe TypeScript Declaration Generator :)

export class SomeTsClass {
	constructor(someArg: string);
}

export namespace client {
	class SuperClientComponent {
		constructor();
		thisIsNice: {bar: string, bow: number};
		saySomething(foo: string): void;
	}
}

export namespace client {
	class Client {
		private constructor();
		static call(): tink.core._Future.FutureObject;
	}
}
